sources:
  - name: raw  
    schema: gz_raw_data  
    tables:
      - name: sales
        freshness: 
            warn_after: {count: 90, period: day}
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
        identifier: raw_gz_sales
        description: sales of greenweez/ we have one row per products_id found in each order_id.
        columns:
          - name: date_date
          - name: pdt_id
          - name: orders_id
          - name: revenue
          - name: qty
        tests:
          - unique:
              column_name: "(pdt_id || '_' || orders_id)"
          - not_null:
              column_name: 
                - pdt_id
                - orders_id
      - name: product
        identifier: raw_gz_product
        description: products of greenweez
        columns:
          - name: products_id
            description: Primary key of the table
            tests:
              - unique
              - not_null
                   
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: Primary key of the table
            tests:
              - unique
              - not_null


            